# Constants for action definitions
ACTION_DRAW_TRAIN_CARDS = 0
ACTION_DRAW_TICKETS = 1
ACTION_CLAIM_ROUTE = 2

# Constants for phases
PHASE_INITIAL_TICKET_SELECTION = 0
PHASE_MAIN = 1
PHASE_DRAW_TRAIN_CARDS = 2
PHASE_CHOOSE_TICKETS = 3
PHASE_CLAIM_ROUTE = 4
PHASE_CHOOSE_PAYMENT = 5
PHASE_FINAL_TICKET_LOSSES = 6

# Routes array indices
COST_ID_INDEX = 2
CLAIMED_BY_INDEX = 3
DRAW_BONUS_INDEX = 5
LENGTH_INDEX = 6
COLOR_INDEX = 7
GAY_CARDS_INDEX = 8
PAYMENT_IDS_INDEX = 9

# Player tickets indices
TICKET_OWNED = 0
TICKET_COMPLETED = 1

# Trajectory indices
STATE_TENSOR_INDEX = 0
REWARD_INDEX = 1
VALUE_INDEX = 2
LOG_ACTION_PROBS_INDEX = 3
ACTION_INDEX = 4
PHASE_INDEX = 5
ACTION_MASK_INDEX = 6